// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadStatusCode int32

const (
	UploadStatusCode_Unknown UploadStatusCode = 0
	UploadStatusCode_Ok      UploadStatusCode = 1
	UploadStatusCode_Failed  UploadStatusCode = 2
)

var UploadStatusCode_name = map[int32]string{
	0: "Unknown",
	1: "Ok",
	2: "Failed",
}

var UploadStatusCode_value = map[string]int32{
	"Unknown": 0,
	"Ok":      1,
	"Failed":  2,
}

func (x UploadStatusCode) String() string {
	return proto.EnumName(UploadStatusCode_name, int32(x))
}

func (UploadStatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

type Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Chunk) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type UploadFileResponse struct {
	Message              string           `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	UploadStatusCode     UploadStatusCode `protobuf:"varint,2,opt,name=UploadStatusCode,proto3,enum=protocol.UploadStatusCode" json:"UploadStatusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UploadFileResponse) Reset()         { *m = UploadFileResponse{} }
func (m *UploadFileResponse) String() string { return proto.CompactTextString(m) }
func (*UploadFileResponse) ProtoMessage()    {}
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}

func (m *UploadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileResponse.Unmarshal(m, b)
}
func (m *UploadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileResponse.Marshal(b, m, deterministic)
}
func (m *UploadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileResponse.Merge(m, src)
}
func (m *UploadFileResponse) XXX_Size() int {
	return xxx_messageInfo_UploadFileResponse.Size(m)
}
func (m *UploadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileResponse proto.InternalMessageInfo

func (m *UploadFileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UploadFileResponse) GetUploadStatusCode() UploadStatusCode {
	if m != nil {
		return m.UploadStatusCode
	}
	return UploadStatusCode_Unknown
}

type DownloadFileParams struct {
	FileName             string   `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadFileParams) Reset()         { *m = DownloadFileParams{} }
func (m *DownloadFileParams) String() string { return proto.CompactTextString(m) }
func (*DownloadFileParams) ProtoMessage()    {}
func (*DownloadFileParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}

func (m *DownloadFileParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadFileParams.Unmarshal(m, b)
}
func (m *DownloadFileParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadFileParams.Marshal(b, m, deterministic)
}
func (m *DownloadFileParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadFileParams.Merge(m, src)
}
func (m *DownloadFileParams) XXX_Size() int {
	return xxx_messageInfo_DownloadFileParams.Size(m)
}
func (m *DownloadFileParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadFileParams.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadFileParams proto.InternalMessageInfo

func (m *DownloadFileParams) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type ResChunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResChunk) Reset()         { *m = ResChunk{} }
func (m *ResChunk) String() string { return proto.CompactTextString(m) }
func (*ResChunk) ProtoMessage()    {}
func (*ResChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{3}
}

func (m *ResChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResChunk.Unmarshal(m, b)
}
func (m *ResChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResChunk.Marshal(b, m, deterministic)
}
func (m *ResChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResChunk.Merge(m, src)
}
func (m *ResChunk) XXX_Size() int {
	return xxx_messageInfo_ResChunk.Size(m)
}
func (m *ResChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_ResChunk.DiscardUnknown(m)
}

var xxx_messageInfo_ResChunk proto.InternalMessageInfo

func (m *ResChunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.UploadStatusCode", UploadStatusCode_name, UploadStatusCode_value)
	proto.RegisterType((*Chunk)(nil), "protocol.Chunk")
	proto.RegisterType((*UploadFileResponse)(nil), "protocol.UploadFileResponse")
	proto.RegisterType((*DownloadFileParams)(nil), "protocol.DownloadFileParams")
	proto.RegisterType((*ResChunk)(nil), "protocol.ResChunk")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcf, 0x6e, 0xb2, 0x40,
	0x14, 0xc5, 0x1d, 0x93, 0x4f, 0xf1, 0x6a, 0xbe, 0x92, 0xbb, 0x22, 0xa4, 0x0b, 0x33, 0xe9, 0x82,
	0x74, 0x41, 0x8c, 0xae, 0x9b, 0x2e, 0x30, 0xec, 0xfa, 0x27, 0x63, 0x7c, 0x80, 0x29, 0xdc, 0xb6,
	0x04, 0x9c, 0x21, 0x0c, 0xea, 0x8b, 0xf4, 0x81, 0x1b, 0x21, 0x23, 0x44, 0x16, 0x5d, 0x91, 0xc3,
	0xdc, 0x7b, 0xce, 0xf9, 0x5d, 0x80, 0x44, 0x57, 0x14, 0x96, 0x95, 0xae, 0x35, 0x3a, 0xcd, 0x27,
	0xd1, 0x05, 0x7f, 0x82, 0x7f, 0xd1, 0xf7, 0x51, 0xe5, 0xe8, 0xc1, 0x34, 0xd2, 0xaa, 0x26, 0x55,
	0x7b, 0x6c, 0xc9, 0x82, 0x85, 0xb0, 0x12, 0x7d, 0x70, 0x3e, 0xb3, 0x82, 0x5e, 0xe5, 0x81, 0xbc,
	0xf1, 0x92, 0x05, 0x33, 0x71, 0xd5, 0xfc, 0x04, 0xb8, 0x2f, 0x0b, 0x2d, 0xd3, 0x38, 0x2b, 0x48,
	0x90, 0x29, 0xb5, 0x32, 0x74, 0xf1, 0x7a, 0x21, 0x63, 0xe4, 0x17, 0x35, 0x5e, 0x33, 0x61, 0x25,
	0xc6, 0xe0, 0xb6, 0xf3, 0xbb, 0x5a, 0xd6, 0x47, 0x13, 0xe9, 0xb4, 0xf5, 0xfc, 0xbf, 0xf6, 0x43,
	0xdb, 0x29, 0xbc, 0x9d, 0x10, 0x83, 0x1d, 0xbe, 0x02, 0xdc, 0xea, 0xb3, 0xb2, 0xc9, 0xef, 0xb2,
	0x92, 0x07, 0x73, 0x69, 0x1a, 0xdb, 0xa6, 0x6d, 0xf0, 0x55, 0xf3, 0x07, 0x70, 0x04, 0x99, 0x3f,
	0x58, 0x1f, 0x37, 0xc3, 0x7e, 0x38, 0x87, 0xe9, 0x5e, 0xe5, 0x4a, 0x9f, 0x95, 0x3b, 0xc2, 0x09,
	0x8c, 0xdf, 0x72, 0x97, 0x21, 0xc0, 0x24, 0x96, 0x59, 0x41, 0xa9, 0x3b, 0x5e, 0xff, 0x30, 0x98,
	0x47, 0xba, 0xa2, 0x1d, 0x55, 0xa7, 0x2c, 0x21, 0x7c, 0x06, 0xe8, 0x8e, 0x82, 0x77, 0x1d, 0x58,
	0x93, 0xee, 0xdf, 0xdf, 0x92, 0xf6, 0x6f, 0xc7, 0x47, 0x01, 0xc3, 0x2d, 0x2c, 0xfa, 0x74, 0xd8,
	0xdb, 0x18, 0x52, 0xfb, 0xd8, 0xbd, 0x5a, 0x42, 0x3e, 0x5a, 0xb1, 0x8f, 0x49, 0xf3, 0x7b, 0xf3,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x10, 0x84, 0x77, 0xf9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoreServiceClient is the client API for CoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoreServiceClient interface {
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (CoreService_UploadFileClient, error)
	DownloadFile(ctx context.Context, in *DownloadFileParams, opts ...grpc.CallOption) (CoreService_DownloadFileClient, error)
}

type coreServiceClient struct {
	cc *grpc.ClientConn
}

func NewCoreServiceClient(cc *grpc.ClientConn) CoreServiceClient {
	return &coreServiceClient{cc}
}

func (c *coreServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (CoreService_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CoreService_serviceDesc.Streams[0], "/protocol.CoreService/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreServiceUploadFileClient{stream}
	return x, nil
}

type CoreService_UploadFileClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*UploadFileResponse, error)
	grpc.ClientStream
}

type coreServiceUploadFileClient struct {
	grpc.ClientStream
}

func (x *coreServiceUploadFileClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *coreServiceUploadFileClient) CloseAndRecv() (*UploadFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coreServiceClient) DownloadFile(ctx context.Context, in *DownloadFileParams, opts ...grpc.CallOption) (CoreService_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CoreService_serviceDesc.Streams[1], "/protocol.CoreService/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreServiceDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CoreService_DownloadFileClient interface {
	Recv() (*ResChunk, error)
	grpc.ClientStream
}

type coreServiceDownloadFileClient struct {
	grpc.ClientStream
}

func (x *coreServiceDownloadFileClient) Recv() (*ResChunk, error) {
	m := new(ResChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CoreServiceServer is the server API for CoreService service.
type CoreServiceServer interface {
	UploadFile(CoreService_UploadFileServer) error
	DownloadFile(*DownloadFileParams, CoreService_DownloadFileServer) error
}

// UnimplementedCoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCoreServiceServer struct {
}

func (*UnimplementedCoreServiceServer) UploadFile(srv CoreService_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (*UnimplementedCoreServiceServer) DownloadFile(req *DownloadFileParams, srv CoreService_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}

func RegisterCoreServiceServer(s *grpc.Server, srv CoreServiceServer) {
	s.RegisterService(&_CoreService_serviceDesc, srv)
}

func _CoreService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoreServiceServer).UploadFile(&coreServiceUploadFileServer{stream})
}

type CoreService_UploadFileServer interface {
	SendAndClose(*UploadFileResponse) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type coreServiceUploadFileServer struct {
	grpc.ServerStream
}

func (x *coreServiceUploadFileServer) SendAndClose(m *UploadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *coreServiceUploadFileServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CoreService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServiceServer).DownloadFile(m, &coreServiceDownloadFileServer{stream})
}

type CoreService_DownloadFileServer interface {
	Send(*ResChunk) error
	grpc.ServerStream
}

type coreServiceDownloadFileServer struct {
	grpc.ServerStream
}

func (x *coreServiceDownloadFileServer) Send(m *ResChunk) error {
	return x.ServerStream.SendMsg(m)
}

var _CoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.CoreService",
	HandlerType: (*CoreServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _CoreService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _CoreService_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}
